FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY *.sln .
COPY BirthdayRoomsBackend/*.csproj ./BirthdayRoomsBackend/
RUN dotnet restore

COPY . .
WORKDIR /src/BirthdayRoomsBackend
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

EXPOSE 80
ENTRYPOINT ["dotnet", "BirthdayRoomsBackend.dll"]